spring:
  application:
    name: homework2
  datasource:
    url: jdbc:postgresql://localhost:5432/homework2db
    username: postgres
    password: asd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true